{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPFjZ/7VhHAZv5WAjpaBeaF"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "tarefas = []\n",
        "proximo_id = 1\n",
        "\n",
        "\n",
        "def exibir_menu():\n",
        "    print(\"\\n\" + \"=\" * 40)\n",
        "    print(\"GERENCIADOR DE TAREFAS\")\n",
        "    print(\"=\" * 40)\n",
        "    print(\"1 - Adicionar tarefa\")\n",
        "    print(\"2 - Listar tarefas\")\n",
        "    print(\"3 - Concluir tarefa\")\n",
        "    print(\"4 - Remover tarefa\")\n",
        "    print(\"5 - Sair\")\n",
        "    print(\"=\" * 40)\n",
        "\n",
        "\n",
        "def adicionar_tarefa():\n",
        "    global proximo_id\n",
        "\n",
        "    print(\"\\n--- ADICIONAR TAREFA ---\")\n",
        "\n",
        "    titulo = input(\"Tarefa: \").strip()\n",
        "\n",
        "    if not titulo:\n",
        "        print(\"O nome da tarefa não pode estar vazio.\")\n",
        "        return\n",
        "\n",
        "    materia = input(\"Matéria: \").strip()\n",
        "\n",
        "    tarefa = {\n",
        "        \"id\": proximo_id,\n",
        "        \"titulo\": titulo,\n",
        "        \"materia\": materia if materia else \"Geral\",\n",
        "        \"concluida\": False\n",
        "    }\n",
        "\n",
        "    tarefas.append(tarefa)\n",
        "    print(f\"Tarefa adicionada com sucesso. ID: {proximo_id}\")\n",
        "\n",
        "    proximo_id += 1\n",
        "\n",
        "\n",
        "def listar_tarefas():\n",
        "    print(\"\\n--- LISTA DE TAREFAS ---\")\n",
        "\n",
        "    if not tarefas:\n",
        "        print(\"Nenhuma tarefa cadastrada.\")\n",
        "        return\n",
        "\n",
        "    for tarefa in tarefas:\n",
        "        status = \"Concluída\" if tarefa[\"concluida\"] else \"Pendente\"\n",
        "\n",
        "        print(\n",
        "            f\"ID: {tarefa['id']} | \"\n",
        "            f\"{status} | \"\n",
        "            f\"{tarefa['titulo']} | \"\n",
        "            f\"{tarefa['materia']}\"\n",
        "        )\n",
        "\n",
        "\n",
        "def encontrar_tarefa(id_tarefa):\n",
        "    for tarefa in tarefas:\n",
        "        if tarefa[\"id\"] == id_tarefa:\n",
        "            return tarefa\n",
        "\n",
        "    return None\n",
        "\n",
        "\n",
        "def concluir_tarefa():\n",
        "    print(\"\\n--- CONCLUIR TAREFA ---\")\n",
        "\n",
        "    if not tarefas:\n",
        "        print(\"Nenhuma tarefa cadastrada.\")\n",
        "        return\n",
        "\n",
        "    try:\n",
        "        id_tarefa = int(input(\"ID da tarefa: \"))\n",
        "    except ValueError:\n",
        "        print(\"Digite um número válido.\")\n",
        "        return\n",
        "\n",
        "    tarefa = encontrar_tarefa(id_tarefa)\n",
        "\n",
        "    if tarefa is None:\n",
        "        print(\"Tarefa não encontrada.\")\n",
        "        return\n",
        "\n",
        "    if tarefa[\"concluida\"]:\n",
        "        print(\"A tarefa já está concluída.\")\n",
        "        return\n",
        "\n",
        "    tarefa[\"concluida\"] = True\n",
        "    print(\"Tarefa concluída com sucesso.\")\n",
        "\n",
        "\n",
        "def remover_tarefa():\n",
        "    print(\"\\n--- REMOVER TAREFA ---\")\n",
        "\n",
        "    if not tarefas:\n",
        "        print(\"Nenhuma tarefa cadastrada.\")\n",
        "        return\n",
        "\n",
        "    try:\n",
        "        id_tarefa = int(input(\"ID da tarefa: \"))\n",
        "    except ValueError:\n",
        "        print(\"Digite um número válido.\")\n",
        "        return\n",
        "\n",
        "    tarefa = encontrar_tarefa(id_tarefa)\n",
        "\n",
        "    if tarefa is None:\n",
        "        print(\"Tarefa não encontrada.\")\n",
        "        return\n",
        "\n",
        "    tarefas.remove(tarefa)\n",
        "    print(\"Tarefa removida com sucesso.\")\n",
        "\n",
        "\n",
        "while True:\n",
        "    exibir_menu()\n",
        "\n",
        "    try:\n",
        "        opcao = int(input(\"Escolha uma opção: \"))\n",
        "    except ValueError:\n",
        "        print(\"Digite um número válido.\")\n",
        "        continue\n",
        "\n",
        "    if opcao == 1:\n",
        "        adicionar_tarefa()\n",
        "\n",
        "    elif opcao == 2:\n",
        "        listar_tarefas()\n",
        "\n",
        "    elif opcao == 3:\n",
        "        concluir_tarefa()\n",
        "\n",
        "    elif opcao == 4:\n",
        "        remover_tarefa()\n",
        "\n",
        "    elif opcao == 5:\n",
        "        print(\"Programa encerrado.\")\n",
        "        break\n",
        "\n",
        "    else:\n",
        "        print(\"Opção inválida.\")"
      ],
      "metadata": {
        "id": "6YbDyfAUtRzE"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}